[tool.autopep8]
max_line_length = 79

[tool.pylint.masters]
jobs = 0
extension-pkg-whitelist = ["pygame"]

[tool.pylint.messages_control]
disable = ["unsubscriptable-object", "too-many-lines"]

[tool.pylint.reports]
output-format = "text"
reports = "yes"

[tool.pylint.basic]
good-names = ["df", "im", "fp"]

[tool.pylint.format]
expected-line-ending-format = "LF"
max-line-length = 79

[tool.pylint.miscellaneous]
notes = ["FIXME", "TODO"]
